### ISSUE TITLE
Files Can't be Opened Properly When this is Imported as a Package

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/dad-python#1]
It appears that we can't open the json files when importing this as a package because it can't find the files relatively. I'll need to do a bit of digging into how to open files in a package context (when this gets included into another piece of software)

```
jhammond@easypost-dev $ venv/bin/python '/Users/jhammond/git/easypost/easypost-dev/src/devvm/python/dad.py'
Traceback (most recent call last):
  File "/Users/jhammond/git/easypost/easypost-dev/src/devvm/python/dad.py", line 3, in <module>
    address = dad_tool.random_address('us_ut')
  File "/Users/jhammond/.venv/easypost-tools/lib/python3.9/site-packages/dad_tool/data_router.py", line 12, in random_address
    address_json = _open_json_file(data)
  File "/Users/jhammond/.venv/easypost-tools/lib/python3.9/site-packages/dad_tool/data_router.py", line 24, in _open_json_file
    with open(address_file, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'dad/src/addresses/united-states/ut-addresses.min.json'
```

**Comment by Justintime50** [comment]
This was fixed via finding out the proper way to package non-Python assets: https://gist.github.com/Justintime50/079a9e287d8afa1ae78773ae373f7829
